import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml"
]

[cursor]
style = "block"
unfocused_hollow = true

[env]
TERM = "alacritty"

[font]
size = 11

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "~"
key = "Ã‘"
mods = "Alt"

[[keyboard.bindings]]
chars = '\'
key = 10
mods = "Alt"

[[keyboard.bindings]]
chars = "|"
key = 18
mods = "Alt"

[[keyboard.bindings]]
chars = "@"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "#"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "{"
key = 39
mods = "Alt"

[[keyboard.bindings]]
chars = "}"
key = 42
mods = "Alt"

[[keyboard.bindings]]
chars = "["
key = 33
mods = "Alt"

[[keyboard.bindings]]
chars = "]"
key = 30
mods = "Alt"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[window]
decorations = "buttonless"

[window.class]
instance = "Alacritty"

[window.dimensions]
columns = 182
lines = 53

[window.padding]
x = 10
y = 10
